version = 1

test_patterns = [
  "tests/**",
  "test_*.py"
]

exclude_patterns = [
  ".github",
  "docs",
  "pure_protobuf/legacy.py",
  "pure_protobuf/six.py"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
  "max_line_length" = 119
