language: python
dist: xenial
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install --upgrade flake8 isort pytest
script:
  - pytest
  - flake8 pure_protobuf tests
  - isort -rc -c pure_protobuf tests
