language: python
dist: xenial
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install --upgrade -e .[dev]
script:
  - pytest --cov-report term-missing --cov pure_protobuf
  - flake8 pure_protobuf tests
  - isort -rc -c --diff pure_protobuf tests
