name: check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install
      run: make venv

    - name: Test
      run: make check/pytest

    - name: Lint
      run: make check/flake8 check/isort check/mypy

    - name: Coveralls
      if: matrix.python-version == '3.10'
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: venv/bin/coveralls
