name: Docs

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: "📥 Checkout"

      - uses: actions/setup-python@v4
        name: "✨ Set up Python"
        with:
          python-version: 3.x

      - uses: actions/cache@v3
        name: "🗃 Cache"
        with:
          key: "mkdocs"
          path: ".cache"

      - run: pip install mkdocs-material
        name: "📥 Install Material for MkDocs"

      - run: mkdocs gh-deploy --force
        name: "📦 Deploy"
