name: Docs

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: "📥 Checkout"

      - uses: actions/setup-python@v4
        name: "✨ Set up Python"
        with:
          python-version: 3.x

      - uses: actions/cache@v3
        name: "🗃 Cache"
        with:
          key: "mkdocs"
          path: "~/.cache"

      - name: "📥 Install Material for MkDocs"
        run: "pip install 'mkdocs-material>=9.0.12,<10.0.0'"

      - run: "mkdocs build --site-dir ${{ runner.temp }}/docs"
        name: "📦 Build"

      - name: "📤 Upload"
        uses: actions/upload-pages-artifact@v1
        with:
          path: "${{ runner.temp }}/docs"

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs: "build"
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: "✨ Deploy"
        uses: actions/deploy-pages@v1
